import type { CompetitorSeed } from "@/lib/types";

export const competitorSeeds: CompetitorSeed[] = [
  { name: "Happy Live", platform: "facebook", source: "trong_nuoc", segmentation: "Bán sách", category: "ban_sach", channelUrl: "https://web.facebook.com/KBApham" },
  { name: "Thái Phạm", platform: "facebook", source: "trong_nuoc", segmentation: "KOL đào tạo", category: "kol_dao_tao", channelUrl: "https://web.facebook.com/happy.live.invest" },
  { name: "Cú Thông Thái", platform: "facebook", source: "trong_nuoc", segmentation: "KOL đào tạo", category: "kol_dao_tao", channelUrl: "https://web.facebook.com/CuThongThai.VNInvestor" },
  { name: "Viện Cổ Phiếu Truongmoney", platform: "facebook", source: "trong_nuoc", segmentation: "KOL đào tạo", category: "kol_dao_tao", channelUrl: "https://web.facebook.com/viencophieu" },
  { name: "Đầu Tư Chứng Khoán Cùng Quang Dũng", platform: "facebook", source: "trong_nuoc", segmentation: "KOL đào tạo", category: "kol_dao_tao", channelUrl: "https://web.facebook.com/profile.php?id=100057330173171" },
  { name: "AzFin Việt Nam", platform: "facebook", source: "trong_nuoc", segmentation: "KOL đào tạo", category: "kol_dao_tao", channelUrl: "https://web.facebook.com/AzFinVietNam" },
  { name: "MInvest", platform: "facebook", source: "trong_nuoc", segmentation: "KOL đào tạo", category: "kol_dao_tao", channelUrl: "https://web.facebook.com/minvest.vn" },
  { name: "Duy Nghiêm", platform: "tiktok", source: "trong_nuoc", category: "other", topicDescription: "Đầu tư - Tài chính - Kinh tế", channelUrl: "https://www.tiktok.com/@duynghiem93" },
  { name: "Ngân Talk", platform: "tiktok", source: "trong_nuoc", category: "other", topicDescription: "Phân tích vàng và bitcoin", channelUrl: "https://www.tiktok.com/@ngantalk.29" },
  { name: "Đào Thịnh Vượng", platform: "tiktok", source: "trong_nuoc", category: "other", topicDescription: "Lời khuyên về đầu tư", channelUrl: "https://www.tiktok.com/@daothinhvuongofficial255" },
  { name: "Kiến thức đầu tư", platform: "tiktok", source: "trong_nuoc", category: "other", topicDescription: "Học đầu tư chứng khoán, crypto A-Z", channelUrl: "https://www.tiktok.com/@nnh.kienthucdautu" },
  { name: "beyondrvn", platform: "tiktok", source: "trong_nuoc", category: "other", topicDescription: "Kỹ năng phân tích giao dịch", channelUrl: "https://www.tiktok.com/@beyondrvn" },
  { name: "truongan.crypto", platform: "tiktok", source: "trong_nuoc", category: "other", topicDescription: "Phân tích thị trường crypto", channelUrl: "https://www.tiktok.com/@truongan.crypto" },
  { name: "The Rich Dad Channel", platform: "youtube", source: "nuoc_ngoai", category: "vi_mo", channelUrl: "https://www.youtube.com/@TheRichDadChannel/videos" },
  { name: "The Trading Channel", platform: "youtube", source: "nuoc_ngoai", category: "ky_thuat", channelUrl: "https://www.youtube.com/@thetradingchannel/videos" },
  { name: "Booming Bulls", platform: "youtube", source: "nuoc_ngoai", category: "ky_thuat", channelUrl: "https://www.youtube.com/@BoomingBulls/videos" },
  { name: "The Trading Greek", platform: "youtube", source: "nuoc_ngoai", category: "ca_hai", channelUrl: "https://www.youtube.com/@TheTradingGeek/featured" },
  { name: "TradingLab", platform: "youtube", source: "nuoc_ngoai", category: "ky_thuat", channelUrl: "https://www.youtube.com/@TradingLabOfficial/videos" },
  { name: "Thái Phạm", platform: "youtube", source: "trong_nuoc", category: "vi_mo", channelUrl: "https://www.youtube.com/@ThaiPhamHappyLive/videos" },
  { name: "Rich Nguyen", platform: "youtube", source: "trong_nuoc", category: "vi_mo", channelUrl: "https://www.youtube.com/@RICHNGUYEN/videos" },
  { name: "GoldSilver", platform: "youtube", source: "nuoc_ngoai", category: "vi_mo", channelUrl: "https://www.youtube.com/@Goldsilver/videos" },
  { name: "Craig Percoco", platform: "youtube", source: "nuoc_ngoai", category: "ky_thuat", channelUrl: "https://www.youtube.com/@craig_percoco/videos" },
  { name: "Trading Strategy Testing", platform: "youtube", source: "nuoc_ngoai", category: "ky_thuat", channelUrl: "https://www.youtube.com/@TradingStrategyTesting/featured" },
  { name: "Duy Thanh Nguyen", platform: "youtube", source: "trong_nuoc", category: "vi_mo", channelUrl: "https://www.youtube.com/@duythanhish/videos" },
  { name: "Riley Coleman", platform: "youtube", source: "nuoc_ngoai", category: "ky_thuat", channelUrl: "https://www.youtube.com/@RileyColeman/videos" },
  { name: "Trade with Pat", platform: "youtube", source: "nuoc_ngoai", category: "ky_thuat", channelUrl: "https://www.youtube.com/@TradewithPat/videos" },
  { name: "Con đường thành công", platform: "youtube", source: "trong_nuoc", category: "vi_mo", channelUrl: "https://www.youtube.com/@conduongthanhcong247/videos" },
  { name: "mInvest", platform: "youtube", source: "trong_nuoc", category: "vi_mo", channelUrl: "https://www.youtube.com/@minvestvn/videos" },
  { name: "9 phút kinh doanh", platform: "youtube", source: "trong_nuoc", category: "vi_mo", channelUrl: "https://www.youtube.com/@9PhutKinhDoanhotPha/videos" },
  { name: "Quang Dũng", platform: "youtube", source: "trong_nuoc", category: "vi_mo", channelUrl: "https://www.youtube.com/@DauTuChungKhoanCungQuangDung/videos" },
  { name: "Thuật Tài Vận", platform: "youtube", source: "trong_nuoc", category: "vi_mo", channelUrl: "https://www.youtube.com/@THUATTAIVAN/videos" },
  { name: "TTA Post", platform: "youtube", source: "nuoc_ngoai", category: "vi_mo", channelUrl: "https://www.youtube.com/@TTAPost/videos" },
  { name: "Trọng tài chính", platform: "youtube", source: "trong_nuoc", category: "ca_hai", channelUrl: "https://www.youtube.com/@trongtaichinh88/videos" },
  { name: "Hoàng Vinh", platform: "youtube", source: "trong_nuoc", category: "vi_mo", channelUrl: "https://www.youtube.com/@hoangvinhdautubenvung/videos" },
  { name: "CHẮC CHẮN THÀNH CÔNG", platform: "youtube", source: "trong_nuoc", category: "vi_mo", channelUrl: "https://www.youtube.com/@chacchanthanhcong/videos" }
];
